// Batch size used when flushing buffered audit logs to the database.
export const DEFAULT_DB_BATCH_SIZE = 25;

/**
 * Insert rows in batches inside a single, real transaction, so a failure
 * partway through leaves no rows behind.
 *
 * The driver split is load-bearing, not cosmetic. better-sqlite3's
 * `transaction()` is synchronous: it runs BEGIN, invokes the callback, then
 * COMMIT. An `async` callback returns a promise at its first `await`, so COMMIT
 * fires on an empty transaction before any insert has executed - the inserts
 * then run afterwards in autocommit mode, one implicit transaction per batch,
 * and the surrounding try/catch cannot observe their rejections either. Driving
 * them synchronously is what makes the transaction real on SQLite.
 * node-postgres is genuinely async and keeps the awaited form.
 *
 * `database` and `table` are parameters rather than module imports so this can
 * be exercised directly against a real database in tests.
 *
 * The `any` types are unavoidable here: only one driver's types exist per build
 * (server/db/index.ts is generated by `npm run set:sqlite` / `set:pg`), so
 * whichever branch is inactive cannot typecheck against the active driver's
 * signature - under the pg build the sqlite branch fails with "Property 'run'
 * does not exist on type 'PgInsertBase'", and under sqlite the pg branch's
 * async callback is likewise rejected.
 */
export async function insertRowsAtomically(
    database: any,
    driverKind: "pg" | "sqlite",
    table: any,
    rows: unknown[],
    batchSize: number = DEFAULT_DB_BATCH_SIZE
): Promise<void> {
    if (rows.length === 0) {
        return;
    }

    if (driverKind === "sqlite") {
        database.transaction((tx: any) => {
            for (let i = 0; i < rows.length; i += batchSize) {
                tx.insert(table)
                    .values(rows.slice(i, i + batchSize))
                    .run();
            }
        });
        return;
    }

    await database.transaction(async (tx: any) => {
        for (let i = 0; i < rows.length; i += batchSize) {
            await tx.insert(table).values(rows.slice(i, i + batchSize));
        }
    });
}
